### PR TITLE
chore(package): upgrade axe-core

### PR DESCRIPTION
**Pull request by badtant**
As requested in https://github.com/crawlkit/runner-axe/issues/147

### CODE REVIEW

**Comment by joscha** [comment]
Thanks! Are you sure the HTML `lang` attribute is correctly represented with no errors in 2.x?

**Comment by badtant** [comment]
didn't look into it that much. just looked at what the response was :)

**Comment by badtant** [comment]
turned out that the rule name had changed. i've fixed that now. so should be good to merge!

**Comment by joscha** [comment]
Thank you @badtant - new release should be imminent - let me know if it worked, on phone only.

**Comment by badtant** [comment]
doesn't seem to be any new release. so please look at that :)

**Comment by joscha** [comment]
Semantic release failed ;(
```
> semantic-release pre && npm publish && semantic-release post
npm ERR! publish Failed PUT 401
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.7.2/bin/node" "/home/travis/.nvm/versions/node/v4.7.2/bin/npm" "publish"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code E401
npm ERR! You must be logged in to publish packages : crawlkit-runner-axe
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/crawlkit/runner-axe/npm-debug.log
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.7.2/bin/node" "/home/travis/.nvm/versions/node/v4.7.2/bin/npm" "run" "semantic-release"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! crawlkit-runner-axe@ semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crawlkit-runner-axe@ semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! This is most likely a problem with the crawlkit-runner-axe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crawlkit-runner-axe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls crawlkit-runner-axe
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/crawlkit/runner-axe/npm-debug.log
```
Will look at it once I am not mobile...

**Comment by joscha** [comment]
`1.0.3` is out

**Comment by badtant** [comment]
I got this message when installing:

npm ERR! crawlkit-runner-axe@1.0.3 postinstall: `validate-commit-msg`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the crawlkit-runner-axe@1.0.3 postinstall script 'validate-commit-msg'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the crawlkit-runner-axe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     validate-commit-msg
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crawlkit-runner-axe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls crawlkit-runner-axe
npm ERR! There is likely additional logging output above.

**Comment by joscha** [comment]
This was a direct install in the cloned repo, right? Which version of node?

**Comment by badtant** [comment]
No, it's when I have 1.0.3 as a dependency to my project. Node 6.9.1

**Comment by joscha** [comment]
fixed via 248b421 in `1.0.4`, sorry about that.

**Pull request merged**
